name: iOS XCUITests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  xcuitests:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Grant Location Permission
        run: xcrun simctl privacy booted grant location c-lo.TrainBusChatBot

      - name: Run XCUITests
        run: |
          xcodebuild \
            -scheme "TrainBusChatBot" \
            -destination 'platform=iOS Simulator,name=iPhone 16 Pro' \
            test
